name: Build and Test Compiler

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t idv-compiler .
      - name: Save Image
        run: docker save idv-compiler > idv-compiler.tar
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiler-image
          path: idv-compiler.tar

  init-test:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: compiler-image
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Init Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app idv-compiler /bin/bash -c "
            mkdir -p build && 
            cmake -B build -S . && 
            cmake --build build && 
            ./build/IDV --gtest_filter=InitTest.*
          "
  init-test-branch1:
    needs: init-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: compiler-image
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Init Test on Branch
        run: ./build/IDV --gtest_filter=InitTest.*

    init-test-branch2:
    needs: init-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: compiler-image
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Init Test on Branch
        run: ./build/IDV --gtest_filter=InitTest.*