name: Build and Test Compiler

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t idv-compiler .
      - name: Save Image
        run: docker save idv-compiler > idv-compiler.tar
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiler-image
          path: idv-compiler.tar

  compile-project:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image
        uses: actions/download-artifact@v4
        with: { name: compiler-image }
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Compile
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app idv-compiler /bin/bash -c "mkdir -p build && cmake -B build -S . && cmake --build build"
      - name: Upload Compiled Binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-build
          path: build/

  init-test-branch1:
    needs: compile-project 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image and Build
        uses: actions/download-artifact@v4
        with: { name: compiler-image }
      - uses: actions/download-artifact@v4
        with: { name: compiled-build, path: build }
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app idv-compiler ./build/IDV --gtest_filter=InitTest.*

  init-test-branch2:
    needs: compile-project 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image and Build
        uses: actions/download-artifact@v4
        with: { name: compiler-image }
      - uses: actions/download-artifact@v4
        with: { name: compiled-build, path: build }
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app idv-compiler ./build/IDV --gtest_filter=InitTest.*

    init-test-branch3:
    needs: init-test-branch3 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image and Build
        uses: actions/download-artifact@v4
        with: { name: compiler-image }
      - uses: actions/download-artifact@v4
        with: { name: compiled-build, path: build }
      - name: Load Image
        run: docker load < idv-compiler.tar
      - name: Run Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app idv-compiler ./build/IDV --gtest_filter=InitTest.*